/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type {
  FunctionFragment,
  Result,
  EventFragment,
} from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export declare namespace HY_lottery {
  export type LotteryStruct = {
    paused: PromiseOrValue<boolean>;
    poolId: PromiseOrValue<BigNumberish>;
    players: PromiseOrValue<string>[];
    lastOpenTimestamp: PromiseOrValue<BigNumberish>;
    lastWinTimestamp: PromiseOrValue<BigNumberish>;
    recentWinner: PromiseOrValue<string>;
  };

  export type LotteryStructOutput = [
    boolean,
    BigNumber,
    string[],
    BigNumber,
    BigNumber,
    string
  ] & {
    paused: boolean;
    poolId: BigNumber;
    players: string[];
    lastOpenTimestamp: BigNumber;
    lastWinTimestamp: BigNumber;
    recentWinner: string;
  };

  export type PoolStruct = {
    onlyHolders: PromiseOrValue<boolean>;
    maxTickets: PromiseOrValue<BigNumberish>;
    ticketPrice: PromiseOrValue<BigNumberish>;
    winnerPerc: PromiseOrValue<BigNumberish>;
    maxTime: PromiseOrValue<BigNumberish>;
    isLotteryActive: PromiseOrValue<boolean>;
    history: HY_lottery.LotteryStruct[];
  };

  export type PoolStructOutput = [
    boolean,
    BigNumber,
    BigNumber,
    BigNumber,
    BigNumber,
    boolean,
    HY_lottery.LotteryStructOutput[]
  ] & {
    onlyHolders: boolean;
    maxTickets: BigNumber;
    ticketPrice: BigNumber;
    winnerPerc: BigNumber;
    maxTime: BigNumber;
    isLotteryActive: boolean;
    history: HY_lottery.LotteryStructOutput[];
  };
}

export interface HY_lotteryInterface extends utils.Interface {
  functions: {
    "buyTickets(uint256,uint256)": FunctionFragment;
    "getActualLottery(uint256)": FunctionFragment;
    "getActualPlayers(uint256)": FunctionFragment;
    "getActualPlayersLength(uint256)": FunctionFragment;
    "getCasinoVault()": FunctionFragment;
    "getEnabledPools()": FunctionFragment;
    "getHYPAaddress()": FunctionFragment;
    "getHustlersaddress()": FunctionFragment;
    "getPool(uint256)": FunctionFragment;
    "getPoolHistory(uint256)": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "resetAndCloseLottery(uint256)": FunctionFragment;
    "setEnabledPools(uint256[])": FunctionFragment;
    "setLotteryPaused(uint256,bool)": FunctionFragment;
    "setPool(uint256,bool,uint256,uint256,uint256,uint256)": FunctionFragment;
    "set_HYPAaddress(address)": FunctionFragment;
    "set_Hustlersaddress(address)": FunctionFragment;
    "set_casinoVault(address)": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
    "withdraw()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "buyTickets"
      | "getActualLottery"
      | "getActualPlayers"
      | "getActualPlayersLength"
      | "getCasinoVault"
      | "getEnabledPools"
      | "getHYPAaddress"
      | "getHustlersaddress"
      | "getPool"
      | "getPoolHistory"
      | "owner"
      | "renounceOwnership"
      | "resetAndCloseLottery"
      | "setEnabledPools"
      | "setLotteryPaused"
      | "setPool"
      | "set_HYPAaddress"
      | "set_Hustlersaddress"
      | "set_casinoVault"
      | "transferOwnership"
      | "withdraw"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "buyTickets",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getActualLottery",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getActualPlayers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getActualPlayersLength",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getCasinoVault",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEnabledPools",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHYPAaddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getHustlersaddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPool",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "getPoolHistory",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "resetAndCloseLottery",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setEnabledPools",
    values: [PromiseOrValue<BigNumberish>[]]
  ): string;
  encodeFunctionData(
    functionFragment: "setLotteryPaused",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<boolean>]
  ): string;
  encodeFunctionData(
    functionFragment: "setPool",
    values: [
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<boolean>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>,
      PromiseOrValue<BigNumberish>
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "set_HYPAaddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "set_Hustlersaddress",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "set_casinoVault",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [PromiseOrValue<string>]
  ): string;
  encodeFunctionData(functionFragment: "withdraw", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buyTickets", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getActualLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActualPlayers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getActualPlayersLength",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCasinoVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEnabledPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHYPAaddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHustlersaddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getPoolHistory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "resetAndCloseLottery",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setEnabledPools",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setLotteryPaused",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPool", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "set_HYPAaddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set_Hustlersaddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "set_casinoVault",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "withdraw", data: BytesLike): Result;

  events: {
    "LotteryEnter(address)": EventFragment;
    "OwnershipTransferred(address,address)": EventFragment;
    "WinnerPicked(address,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "LotteryEnter"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "WinnerPicked"): EventFragment;
}

export interface LotteryEnterEventObject {
  player: string;
}
export type LotteryEnterEvent = TypedEvent<[string], LotteryEnterEventObject>;

export type LotteryEnterEventFilter = TypedEventFilter<LotteryEnterEvent>;

export interface OwnershipTransferredEventObject {
  previousOwner: string;
  newOwner: string;
}
export type OwnershipTransferredEvent = TypedEvent<
  [string, string],
  OwnershipTransferredEventObject
>;

export type OwnershipTransferredEventFilter =
  TypedEventFilter<OwnershipTransferredEvent>;

export interface WinnerPickedEventObject {
  player: string;
  prize: BigNumber;
}
export type WinnerPickedEvent = TypedEvent<
  [string, BigNumber],
  WinnerPickedEventObject
>;

export type WinnerPickedEventFilter = TypedEventFilter<WinnerPickedEvent>;

export interface HY_lottery extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: HY_lotteryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    buyTickets(
      _poolId: PromiseOrValue<BigNumberish>,
      _numTickets: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    getActualLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[HY_lottery.LotteryStructOutput]>;

    getActualPlayers(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[string[]]>;

    getActualPlayersLength(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    getCasinoVault(overrides?: CallOverrides): Promise<[string]>;

    getEnabledPools(overrides?: CallOverrides): Promise<[BigNumber[]]>;

    getHYPAaddress(overrides?: CallOverrides): Promise<[string]>;

    getHustlersaddress(overrides?: CallOverrides): Promise<[string]>;

    getPool(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[HY_lottery.PoolStructOutput]>;

    getPoolHistory(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[HY_lottery.LotteryStructOutput[]]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    resetAndCloseLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setEnabledPools(
      _enabledPools: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setLotteryPaused(
      poolId: PromiseOrValue<BigNumberish>,
      paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setPool(
      _poolId: PromiseOrValue<BigNumberish>,
      _onlyHolders: PromiseOrValue<boolean>,
      _maxTickets: PromiseOrValue<BigNumberish>,
      _ticketPrice: PromiseOrValue<BigNumberish>,
      _winnerPerc: PromiseOrValue<BigNumberish>,
      _maxTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    set_HYPAaddress(
      _HYPAaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    set_Hustlersaddress(
      _Hustlersaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    set_casinoVault(
      _casinoVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    withdraw(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  buyTickets(
    _poolId: PromiseOrValue<BigNumberish>,
    _numTickets: PromiseOrValue<BigNumberish>,
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  getActualLottery(
    _poolId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<HY_lottery.LotteryStructOutput>;

  getActualPlayers(
    _poolId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<string[]>;

  getActualPlayersLength(
    _poolId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  getCasinoVault(overrides?: CallOverrides): Promise<string>;

  getEnabledPools(overrides?: CallOverrides): Promise<BigNumber[]>;

  getHYPAaddress(overrides?: CallOverrides): Promise<string>;

  getHustlersaddress(overrides?: CallOverrides): Promise<string>;

  getPool(
    _poolId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<HY_lottery.PoolStructOutput>;

  getPoolHistory(
    _poolId: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<HY_lottery.LotteryStructOutput[]>;

  owner(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  resetAndCloseLottery(
    _poolId: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setEnabledPools(
    _enabledPools: PromiseOrValue<BigNumberish>[],
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setLotteryPaused(
    poolId: PromiseOrValue<BigNumberish>,
    paused: PromiseOrValue<boolean>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setPool(
    _poolId: PromiseOrValue<BigNumberish>,
    _onlyHolders: PromiseOrValue<boolean>,
    _maxTickets: PromiseOrValue<BigNumberish>,
    _ticketPrice: PromiseOrValue<BigNumberish>,
    _winnerPerc: PromiseOrValue<BigNumberish>,
    _maxTime: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  set_HYPAaddress(
    _HYPAaddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  set_Hustlersaddress(
    _Hustlersaddress: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  set_casinoVault(
    _casinoVault: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: PromiseOrValue<string>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  withdraw(
    overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    buyTickets(
      _poolId: PromiseOrValue<BigNumberish>,
      _numTickets: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    getActualLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<HY_lottery.LotteryStructOutput>;

    getActualPlayers(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<string[]>;

    getActualPlayersLength(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCasinoVault(overrides?: CallOverrides): Promise<string>;

    getEnabledPools(overrides?: CallOverrides): Promise<BigNumber[]>;

    getHYPAaddress(overrides?: CallOverrides): Promise<string>;

    getHustlersaddress(overrides?: CallOverrides): Promise<string>;

    getPool(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<HY_lottery.PoolStructOutput>;

    getPoolHistory(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<HY_lottery.LotteryStructOutput[]>;

    owner(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    resetAndCloseLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    setEnabledPools(
      _enabledPools: PromiseOrValue<BigNumberish>[],
      overrides?: CallOverrides
    ): Promise<void>;

    setLotteryPaused(
      poolId: PromiseOrValue<BigNumberish>,
      paused: PromiseOrValue<boolean>,
      overrides?: CallOverrides
    ): Promise<void>;

    setPool(
      _poolId: PromiseOrValue<BigNumberish>,
      _onlyHolders: PromiseOrValue<boolean>,
      _maxTickets: PromiseOrValue<BigNumberish>,
      _ticketPrice: PromiseOrValue<BigNumberish>,
      _winnerPerc: PromiseOrValue<BigNumberish>,
      _maxTime: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;

    set_HYPAaddress(
      _HYPAaddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    set_Hustlersaddress(
      _Hustlersaddress: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    set_casinoVault(
      _casinoVault: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: CallOverrides
    ): Promise<void>;

    withdraw(overrides?: CallOverrides): Promise<void>;
  };

  filters: {
    "LotteryEnter(address)"(
      player?: PromiseOrValue<string> | null
    ): LotteryEnterEventFilter;
    LotteryEnter(
      player?: PromiseOrValue<string> | null
    ): LotteryEnterEventFilter;

    "OwnershipTransferred(address,address)"(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;
    OwnershipTransferred(
      previousOwner?: PromiseOrValue<string> | null,
      newOwner?: PromiseOrValue<string> | null
    ): OwnershipTransferredEventFilter;

    "WinnerPicked(address,uint256)"(
      player?: PromiseOrValue<string> | null,
      prize?: null
    ): WinnerPickedEventFilter;
    WinnerPicked(
      player?: PromiseOrValue<string> | null,
      prize?: null
    ): WinnerPickedEventFilter;
  };

  estimateGas: {
    buyTickets(
      _poolId: PromiseOrValue<BigNumberish>,
      _numTickets: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    getActualLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getActualPlayers(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getActualPlayersLength(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getCasinoVault(overrides?: CallOverrides): Promise<BigNumber>;

    getEnabledPools(overrides?: CallOverrides): Promise<BigNumber>;

    getHYPAaddress(overrides?: CallOverrides): Promise<BigNumber>;

    getHustlersaddress(overrides?: CallOverrides): Promise<BigNumber>;

    getPool(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getPoolHistory(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    resetAndCloseLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setEnabledPools(
      _enabledPools: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setLotteryPaused(
      poolId: PromiseOrValue<BigNumberish>,
      paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setPool(
      _poolId: PromiseOrValue<BigNumberish>,
      _onlyHolders: PromiseOrValue<boolean>,
      _maxTickets: PromiseOrValue<BigNumberish>,
      _ticketPrice: PromiseOrValue<BigNumberish>,
      _winnerPerc: PromiseOrValue<BigNumberish>,
      _maxTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    set_HYPAaddress(
      _HYPAaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    set_Hustlersaddress(
      _Hustlersaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    set_casinoVault(
      _casinoVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    withdraw(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    buyTickets(
      _poolId: PromiseOrValue<BigNumberish>,
      _numTickets: PromiseOrValue<BigNumberish>,
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    getActualLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getActualPlayers(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getActualPlayersLength(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getCasinoVault(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getEnabledPools(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHYPAaddress(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getHustlersaddress(
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPool(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getPoolHistory(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    resetAndCloseLottery(
      _poolId: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setEnabledPools(
      _enabledPools: PromiseOrValue<BigNumberish>[],
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setLotteryPaused(
      poolId: PromiseOrValue<BigNumberish>,
      paused: PromiseOrValue<boolean>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setPool(
      _poolId: PromiseOrValue<BigNumberish>,
      _onlyHolders: PromiseOrValue<boolean>,
      _maxTickets: PromiseOrValue<BigNumberish>,
      _ticketPrice: PromiseOrValue<BigNumberish>,
      _winnerPerc: PromiseOrValue<BigNumberish>,
      _maxTime: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    set_HYPAaddress(
      _HYPAaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    set_Hustlersaddress(
      _Hustlersaddress: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    set_casinoVault(
      _casinoVault: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: PromiseOrValue<string>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    withdraw(
      overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
